config/routes.rb
BHRobotics::Application.routes.draw do
  get "/welcome" => "welcome#index", :as => :welcome
  get "/webcast" => "welcome#webcast", :as => :webcast

  scope "/about" do
    get "mission" => "about#mission", :as => :mission

    get "members/sign-in" => "members#sign_in", :as => :sign_in
    post "members/sign-in" => "members#check_sign_in", :as => :check_sign_in
    get "members/sign-out" => "members#sign_out", :as => :sign_out
    get "members" => "members#index", :as => :members
    post "members" => "members#create"
    get "members/new" => "members#new", :as => :new_member
    get "members/:id" => "members#show", :as => :member
    put "members/:id" => "members#update"
    delete "members/:id" => "members#destroy"
    get "members/:id/edit" => "members#edit", :as => :edit_member

    scope "/robots" do
      get "rob-2" => "about#rob_2", :as => :rob_2
      get "strikert" => "about#strikert", :as => :strikert
      get "morbit" => "about#morbit", :as => :morbit
      get "orange-fever" => "about#orange_fever", :as => :orange_fever
      get "mad-max" => "about#mad_max", :as => :mad_max
      get "killer-katie" => "about#killer_katie", :as => :killer_katie
      get "norman-1" => "about#norman_1", :as => :norman_1
      get "mettabot" => "about#mettabot", :as => :mettabot
      root :to => "about#mettabot", :as => :robots
    end

    get "awards" => "about#awards", :as => :awards
    get "about-this-website" => "about#about_this_website", :as => :about_this_website
    root :to => "about#mission"
  end

  scope "/media" do
    get "documents" => "media#documents", :as => :documents
    get "calendar" => "media#calendar", :as => :calendar
    root :to => "media#documents"
    get "photos" => "media#photos", :as => :photos
  end

  scope "/partners" do
    get "wdi" => "partners#wdi", :as => :wdi
    get "larop" => "partners#larop", :as => :larop
    get "raytheon" => "partners#raytheon", :as => :raytheon
   # get "redman" => "partners#redman", :as => :redman
    get "asb" => "partners#asb", :as => :asb
    get "wire-edm" => "partners#wire_edm", :as => :wire_edm
    root :to => "partners#wdi"
  end

  scope "/community" do
    scope "/outreach" do
      get "car-show" => "community#car_show", :as => :car_show
      get "ttc" => "community#ttc", :as => :ttc
      get "rmd-charities" => "community#rmd_charities", :as => :rmd_charities
      get "engineering-day" => "community#engineering_day", :as => :engineering_day
      get "k8-contest" => "community#k8_contest", :as => :k8_contest
      get "mda" => "community#mda", :as => :mda
      get "cedars" => "community#cedars", :as => :cedars
      get "hm-breakfast" => "community#hm_breakfast", :as => :hm_breakfast
      get "other-outreach-events" => "community#other_outreach_events", :as => :other_outreach_events
      root :to => "community#outreach", :as => :outreach
    end

    root :to => "community#outreach"
  end

  scope "/first" do
    get "what-is-first" => "first#what_is_first", :as => :what_is_first
    get "rebound-rumble" => "first#rebound_rumble", :as => :rebound_rumble
    get "logomotion" => "first#logomotion", :as => :logomotion
    get "breakaway" => "first#breakaway", :as => :breakaway
    get "lunacy" => "first#lunacy", :as => :lunacy
    get "overdrive" => "first#overdrive", :as => :overdrive
    get "rack-n-roll" => "first#rack_n_roll", :as => :rack_n_roll
    get "aim-high" => "first#aim_high", :as => :aim_high
    get "triple-play" => "first#triple_play", :as => :triple_play
    get "game" => "first#game", :as => :game
    get "heroes-of-first" => "first#heroes_of_first", :as => :heroes_of_first
    get "creating-a-first-website" => "first#creating_a_first_website", :as => :creating_a_first_website
    root :to => "first#what_is_first"
  end

  scope "/welcome" do
    get "webcast" => "welcome#webcast", :as => :webcast
  end
  root :to => "welcome#index"
end

app/controllers/first_controller.rb
class FirstController < ApplicationController
end

app/helpers/first_helper.rb
module FirstHelper
end

app/views/first/Rebound_Rumble.html.erb
<% title " TRUE Rebound Rumble" %>
<% page_class "previous-years" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", logomotion_path, :class => "back" %>
    <%= link_to "Forward", lunacy_path, :class => "forward" %>
    <%= image_tag "games/Rebound_Rumble.jpg", :alt => "Rebound Rumble" %>
  </section>

  <section class="information">
    <h2>2012: Rebound Rumble</h2>
    <p>In the game, Rebound Rumble, it was played between two Alliances of three teams each. Each Alliance competes by trying to score as many of the basketballs in the hoops as possible during the two-minute and 15-second match. Balls scored in higher hoops score teams more points. Team Alliances are awarded bonus points if they are balanced on bridges at the end of the match.</p>
  </section>
</section>

app/views/first/Ultimate Ascent.html.erb
<% title " TRUE Rebound Rumble" %>
<% page_class "previous-years" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", logomotion_path, :class => "back" %>
    <%= link_to "Forward", lunacy_path, :class => "forward" %>
    <%= image_tag "games/breakaway.jpg", :alt => "Breakaway" %>
  </section>

  <section class="information">
    <h2>2010: Breakaway</h2>
    <p>In the game, Breakaway, robots played soccer on a field that had two towers with tunnels underneath and two bumps across the width of the field, dividing the field into three sections. One robot from each alliance was placed in each of the sections and given a certain amount of balls to shoot depending on the distance between the goals. The object of the game was to push the balls into the goals to score points. Near the end of the game, robots could receive extra points if they hung from one of the towers, or from another robot.</p>
  </section>
</section>

app/views/first/aim_high.html.erb
<% title "Aim High" %>
<% page_class "previous-years" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", rack_n_roll_path, :class => "back" %>
    <%= link_to "Forward", triple_play_path, :class => "forward" %>
    <%= image_tag "games/aim-high.jpg", :alt => "Aim High" %>
  </section>

  <section class="information">
    <h2>2006: Aim High</h2>
    <p>In the game, Aim High, robots tried to score goals by mainly shooting balls into a high center target, with floor targets on each side. Each center goal was worth 3 points while the corner, floor goals were worth 1 point. In the last period of the game, teams try to earn bonus points by making their robots climb on top of a platform, placed on either sides of the field. If the succeeded, teams earned up to 25 points.</p>
  </section>
</section>

app/views/first/breakaway.html.erb
<% title "Breakaway" %>
<% page_class "previous-years" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", logomotion_path, :class => "back" %>
    <%= link_to "Forward", lunacy_path, :class => "forward" %>
    <%= image_tag "games/breakaway.jpg", :alt => "Breakaway" %>
  </section>

  <section class="information">
    <h2>2010: Breakaway</h2>
    <p>In the game, Breakaway, robots played soccer on a field that had two towers with tunnels underneath and two bumps across the width of the field, dividing the field into three sections. One robot from each alliance was placed in each of the sections and given a certain amount of balls to shoot depending on the distance between the goals. The object of the game was to push the balls into the goals to score points. Near the end of the game, robots could receive extra points if they hung from one of the towers, or from another robot.</p>
  </section>
</section>

app/views/first/creating_a_first_website.html.erb
<% title "Creating a FIRST Website" %>
<% page_class "creating-a-first-website" %>

<div class="columns">
  <div class="column-1">
    <%= image_tag "headers/creating-a-first-website.jpg", :alt => "Creating a FIRST Website", :class => "header-image" %>
    <h1>Creating a FIRST Website</h1>
    <p>So you want to build your own website for an FRC team? Well, we have some resources here to get your started. You will need:
    <ul>
      <li>Basic computer skills</li>
      <li>A computer with an Internet connection, which you already have if you're here</li>
      <li>A plaintext editor. We recommend <%= link_to "Notepad++", "http://notepad-plus-plus.org/" %> for Windows, <%= link_to "TextMate", "http://macromates.com" %> for Mac, and <%= link_to "gedit", "gedit.sourceforge.net" %> for Linux.</li>
    </ul>

    <h2>Getting Started</h2>
    <p>Websites are made using three languages: HTML, CSS, and JavaScript. HTML stands for HyperText Markup Language and displays the text and images in a web browser. CSS stands for Cascading Style Sheets and adds styles to the various parts of the webpage. JavaScript handles the behavior of the website, like making things on the page move. <%= link_to "HTMLDog", "http://htmldog.com" %> has some fantastic tutorials on each of the three languages. We strongly recommend going through every section of the site to learn the basics of web programming.</p>

    <h2>Designing the Site</h2>
    <p>After you have an idea for what content you want on your FRC team website, it's time to start designing it. Use a tool like Adobe Photoshop and create a simple mockup of what you want the site to look like. Keep in mind that simple designs are usually more effective and easier to program.</p>

    <h2>Time to Program!</h2>
    <p>Once your team has settled on a layout, use your new HTML and CSS skills to turn it into a working website. For right now, you should focus on just using HTML files, and upload them to your webhost of choice. We suggest <%= link_to "HostMonster", "http://hostmonster.com" %>. FIRST awards points for passing the <a href="http://validator.w3.org/">W3C Validator</a>, a website that checks for errors in your website code. Be sure to run this on your website before submitting your site to FIRST!</p>

    <h2>Writing Content</h2>
    <p>The most important part of the website is the written content. FIRST greatly emphasizes this in the <%= link_to "requirements for the Website Award", "http://www.usfirst.org/uploadedFiles/WEBSITE%20AWARD%20Criteria.pdf" %>. On the home page, explain what your team is, where it's based, and information about FIRST. On other pages, go into detail about your team, talking about your team's history, mission, and previous robots. The more information, the better!</p>

    <h2>Integrate Multimedia</h2>
    <p>A website isn't complete without photos and videos. We recommend uploading all your team photos to Picasa and all your team videos to Vimeo. Using <%= link_to "this tutorial", "http://support.google.com/picasa/bin/answer.py?hl=en&answer=66969" %>, embed them into your website.</p>

    <h2>Spreading the Message</h2>
    <p>Throughout your entire website, make sure that you spread the message of FIRST. Your website should have a link to the FIRST website on every page and include a section describing FIRST in detail. Describe this year's game as well, so that visitors know what to expect at this year's competiton. As always, be gaciously professional!</p>
  </div>

  <div class="column-2">
    <h2>Need Help?</h2>
    <p>Feel free to contact us at <%= link_to "contact@bhrobotics.com", "mailto:contact@bhrobotics.com" %>, we're happy to help. If you need to look at the source of this website, just go to <%= link_to "our GitHub", "http://github.com/CapnKernul/bhrobotics.com" %>. Everything is open source and free to use, extend, and rebrand.</p>
  </div>
</div>

app/views/first/game.html.erb
<% title "Ultimate Ascent" %>
<% page_class "rebound-rumble" %>

<div class="columns">
  <div class="column-1">
    <h1>Ultimate Ascent</h1>
    <p>In Ultimate Ascent, each team controls a robot and is in an alliance with two other teams. Each alliance competes by scoring as many baskets as possible in a two-minute and fifteen-second time period. Goals at different heights have varying point values. Teams can also score by climbing the pyramid located at the center of the field. Robots can not be as tall as a team wants them to be. There are rules that the robots and players must follow. If the players or the robots break any of the rules, the team recipes a foul. Fouls can either deduct points or disqualify players or robots.</p>

    <h2>Gameplay</h2>
    <p>Alliances work together to score points by making goals and staying on the pyramid. Robots can either play defense or offense to help their alliance win. A defensive robot tries to stop the other team's offense robot from scoring. An offensive robot scores by successfully shooting throwing discs in goals. Robots can pick up throwing discs from the ground or from a throwing disc feeder. The robots can hold up to four throwing discs at once. Robots can travel from each side of the field by driving forward. The game is played on a field that is 27ft by 54 ft. During the autonomous period, </p>

    <h2>Scoring</h2>
    <p>In Ultimate Ascent points can be scored two ways: by shooting the throwing disc in the goal and by climbing the pyramid in the center of the field. There are four baskets in the game, with one at the top, two in the middle, one on the bottom and a bin on top of the pyramid. Balls scored on the highest hoop are worth three points, balls scored on the middle hoops are worth two points, and balls scored on the lowest hoop are worth one point. Balancing on the bridges is worth more than scoring a basket. There are three bridges, and those on the outside are worth less than the middle bridge, which requires a robot from each team in order to be balanced. Players can use the Kinect to motion-control their robot during the Hybrid Period. Points scored on the baskets are valued differently from the rest of the game. Baskets scored during the Hybrid Period are worth three more points than in the normal game.</p>

    <table>
      <thead>
        <tr>
          <th>Goal</th>
          <th>Autonomous Points</th>
          <th>Teleop Points</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Top</td>
          <td>6</td>
          <td>3</td>
        </tr>
        <tr>
          <td>Middle</td>
          <td>4</td>
          <td>2</td>
        </tr>
        <tr>
          <td>Bottom</td>
          <td>2</td>
          <td>1</td>
        </tr>
        <tr>
          <td>Pyramid goal</td>
          <td> NA </td>
          <td>5</td>
        </tr>
      </tbody>
    </table>

    <table>
      <thead>
        <tr>
          <th>Pyramid levels</th>
          <th>Points</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1st</td>
          <td>10</td>
        </tr>
        <tr>
          <td>2nd</td>
          <td>20</td>
        </tr>
        <tr>
          <td>3th</td>
          <td>30</td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="column-2">
    <figure class="animation">
<iframe width="560" height="315" src="http://www.youtube.com/embed/wa5MGEZNrf0" frameborder="0" allowfullscreen></iframe>
      <figcaption>Game Animation</figcaption>
    </figure>

    <h2>FAQs</h2>
    <ul class="faqs">
      <div class="question">
        <li><em>Q:</em> Are the robots allowed to skip rungs on the pyramid? </li>
        <li><em>A:</em> No. Robots must go on consecutive rungs</li>
      </div>

      <div class="question">
        <li><em>Q:</em> Can we score the last 30 seconds of the match from the feeder?</li>
        <li><em>A:</em> There is no feeder in Rebound Rumble.</li>
      </div>

      <div class="question">
        <li><em>Q:</em> When can the human players throw the throwing discs by hand?</li>
        <li><em>A:</em> In the last 30 seconds of the match.</li>
      </div>

      <div class="question">
        <li><em>Q:</em> When is the throwing disc considered in the goal?</li>
        <li><em>A:</em> When it touches the weight sensor.</li>
      </div>

      <div class="question">
        <li><em>Q:</em> Can an Blue Alliance robot touch a Red Alliance robot when the red robot is touching its alliance's pyramid?</li>
        <li><em>A:</em> No, that is a technical foul.</li>
      </div>

      <div class="question">
        <li><em>Q:</em> Where do robots start in the autonomous period?</li>
        <li><em>A:</em> Robots must be touching the pyramid.</li>
      </div>
    </ul>
  </div>
</div>

app/views/first/logomotion.html.erb
<% title "Logomotion" %>
<% page_class "previous-years" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", triple_play_path, :class => "back" %>
    <%= link_to "Forward", breakaway_path, :class => "forward" %>
    <%= image_tag "games/logomotion.jpg", :alt => "Logomotion" %>
  </section>

  <section class="information">
    <h2>2011: Logomotion</h2>
    <p>Robots stacked inflatable game pieces, in the shapes of the FIRST Logo, on to poles by hanging them from hooks. Teams recieved points for hanging game pieces on any of the three height levels of the hooks, and received more points if they formed the FIRST Logo. During the end of the game, robots released minibots that raced up to the top of one of the poles in the middle of the field to get bonus points.</p>
  </section>
</section>

app/views/first/lunacy.html.erb
<% title "Lunacy" %>
<% page_class "previous-years" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", breakaway_path, :class => "back" %>
    <%= link_to "Forward", overdrive_path, :class => "forward" %>
    <%= image_tag "games/lunacy.jpg", :alt => "Lunacy" %>
  </section>

  <section class="information">
    <h2>2009: Lunacy</h2>
    <p>The object of the game was to have robots and humans score points by shooting "balls" into trailers attached to the end of each robot. There were three different types of "balls": Moon Rocks and Empty Cells were worth two points each and Super Cells were worth 15.</p>
  </section>
</section>

app/views/first/overdrive.html.erb
<% title "FIRST Overdrive" %>
<% page_class "previous-years" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", lunacy_path, :class => "back" %>
    <%= link_to "Forward", rack_n_roll_path, :class => "forward" %>
    <%= image_tag "games/overdrive.jpg", :alt => "Overdrive" %>
  </section>

  <section class="information">
    <h2>2008: FIRST Overdrive</h2>
    <p>FIRST Overdrive simulated a car race with the objective of each team’s robots crossing their finish lines multiple times. Besides passing the finish line, there were track balls suspended on an overpass, which could be knocked down and pushed across the finish line to earn more points. Each time a robot finished a lap or a ball passed the finish line, the team received two points, but if the ball went over the overpass, they received 8 points. During the finale of the game, robots could attempt to place the balls back on the overpass, but they had to stay there until the end of the game.</p>
  </section>
</section>

app/views/first/rack_n_roll.html.erb
<% title "Rack 'n Roll" %>
<% page_class "previous-years" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", overdrive_path, :class => "back" %>
    <%= link_to "Forward", aim_high_path, :class => "forward" %>
    <%= image_tag "games/rack-n-roll.jpg", :alt => "Rack 'n Roll" %>
  </section>

  <section class="information">
    <h2>2007: Rack 'n Roll</h2>
    <p>Rack 'n Roll was a game where robots competed to hang three types of inflatable pool tubes on to a rack in the middle of the field that had 3 hooks obtruding in 8 columns (24 hooks in total). The three types of pool tubes were as follows: Keepers- printed pool tubes that were used during the autonomos period and couldn’t be moved after they were hung, Ringers- plain pool tubes that were used during the teleoperated period, and Spoilers- black pool tubes that blocked hooks and were movable. Teams scored points by making rows and columns using their designated tubes. At the end of the game, teams received points on how many 2-tube and 3-tube rows and columns they made on the racks.</p>
  </section>
</section>

app/views/first/rebound_rumble.html.erb
<% title " TRUE Rebound Rumble" %>
<% page_class "previous-years" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", logomotion_path, :class => "back" %>
    <%= link_to "Forward", lunacy_path, :class => "forward" %>
    <%= image_tag "games/Rebound_Rumble.jpg", :alt => "Rebound Rumble" %>
  </section>

  <section class="information">
    <h2>2012: Rebound Rumble</h2>
    <p>In the game, Rebound Rumble, it was played between two Alliances of three teams each. Each Alliance competes by trying to score as many of the basketballs in the hoops as possible during the two-minute and 15-second match. Balls scored in higher hoops score teams more points. Team Alliances are awarded bonus points if they are balanced on bridges at the end of the match.</p>
  </section>
</section>

app/views/first/triple_play.html.erb
<% title "Triple Play" %>
<% page_class "previous-years" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", aim_high_path, :class => "back" %>
    <%= link_to "Forward", logomotion_path, :class => "forward" %>
    <%= image_tag "games/triple-play.jpg", :alt => "Triple Play" %>
  </section>

  <section class="information">
    <h2>2005: Triple Play</h2>
    <p>The object of Triple Play was to score points by stacking tetrads (tetrahedrons) on top of goal posts or by dropping the game pieces beneath the goals. Each stacked tetrahedron was worth three points, while the dropped game pieces were worth one. Teams could also earn bonus points by making a row of three tetrads or by pushing all of their robots into their assigned end zones.</p>
  </section>
</section>

app/views/first/what_is_first.html.erb
<% title "What is FIRST?" %>
<% page_class "what-is-first" %>

<div class="columns">
  <div class="column-1">
    <%= image_tag "headers/what-is-first.jpg", :alt => "What is FIRST?", :class => "header-image" %>
    <h1>What is FIRST?</h1>
    <p>FIRST (For Inspiration and Recognition of Science and Technology) is a robotics program that encourages young people aged 6-18 to be leaders in the fields of science and technology. In FIRST, students participate in diverse competitions in which they build robots and compete with them in a game at the end of the “building season”. Through these programs for young people, FIRST attempts to help young people uncover and cultivate a passion for science, engineering, technology, and math. FIRST’s goal is to spur students to innovate, build life skills, create self-confidence, and form communication and leadership skills.</p>
    <p>FIRST emphasizes the concept of “Gracious Professionalism,” a term coined by FIRST co-founder Dr. Woodie Flowers. Gracious Professionalism is a way of action consistent with producing one’s best work while respecting others at the same time. Gracious Professionalism blends the spirit of competition with mutual gain to help students become kind, respectful, and helpful to one another. Another FIRST term, “Coopertition,” like Gracious Professionalism, is about being compassionate and respectful even during intense competition. Coopertition encourages different teams to aid and collaborate with each other at all times, even in the heat of competition.</p>

    <h2>FIRST Robotics Competition</h2>
    <p>The FIRST Robotics Competition is an international high school robotics competition organized by FIRST (For Inspiration and Recognition of Science and Technology). Each year, teams of high school students compete to build robots weighing up to 120 pounds (54 kg), not including battery and bumpers, that can complete a specific set of tasks (the “Game”), which change every year. Teams are given a standard set of parts and the game details at the beginning of January and have six weeks to construct a competitive robot that can operate both autonomously and when guided by wireless controls to complete the assigned tasks.</p>

    <h2>History of FIRST</h2>
    <p>FIRST was founded in 1989 by Dean Kamen. The competition, which began with 28 teams competing in a New Hampshire high school’s gymnasium, has since been held in locations all over the country, including the Epcot Center in Orlando, Reliant Park in Houston, the Georgia Dome in Atlanta, and, since 1995, the Edward Jones Dome in St. Louis.</p>
    <p>Dean Kamen, the founder of FIRST, also founded AutoSyringe, Inc. and DEKA Research and Development Corporation. He has earned 440 international patents on diverse inventions like the Segway, the wearable infusion and insulin pump, and the portable dialysis machine. Dean Kamen has spent his life advancing the lives of the less fortunate and encouraging students to become involved in the fields of science and technology. Mr. Kamen has won the National Medal of Technology award (2000), the Lemelson-MIT Prize (2002), and was inducted into the National Inventors Hall of Fame in 2005.</p>
    <p>Dr. Woodie Flowers is the co-founder of FIRST, the creator of the term “gracious professionalism,” the FIRST National Advisor, and a former member of the Game and Kit Design Committee. In his honor, the Woodie Flowers Award is presented each year to mentors who contribute meaningfully to their team. Dr. Flowers is currently the Pappalardo Professor Emeritus of Mechanical Engineering at Massachusetts Institute of Technology, a Distinguished Partner at Olin College, a member of the National Academy of Engineering, a Fellow of the American Association for the Advancement of Science and of the American Society of Mechanical Engineers, and a MacVicar Faculty Fellow. At MIT, Dr. Flowers was instrumental in developing MIT's acclaimed course "Introduction to Design." Dr. Flowers’ areas of expertise are engineering, design, and product development. He has been the recipient of a New England EMMY Award for a special PBS program on design, The Joel and Ruth Spria Outstanding Design Educator Award from ASME, a Public Service Medal from NASA, and a Doctor Honoris Causa from Andreas Bello University in Chile. Dr. Flowers received national acknowledgment for his role as a host on the PBS television series Scientific American Frontiers from 1990 to 1993.</p>

    <h2>Get Involved!</h2>
    <p>There are many ways to get involved with FIRST. The first way is to join an existing team in your region. This can easily be done by contacting your FIRST Regional Director or local teams. If there are no existing teams near you, consider starting a team yourself. Another real form of participation in the FIRST community is attendance at regional/international competitions, where you will cheer on and interact with the many teams that participate in competitions every year. Another way to get involved with FIRST is to focus on spreading its (and our) message by educating youth on the joys of science and technology.</p>
    <p>FIRST is always looking for additional support. Please visit the FIRST for information on how to donate, mentor, or volunteer at competitions.</p>
  </div>

  <div class="column-2">
    <h2>Rebound Rumble</h2>
    <p>The 2012 FRC game is “Rebound Rumble.” In this game, two “alliances” of three teams each compete by shooting as many basketballs into hoops as possible in the 2 minute and 15 second segments of the game. Additional points are awarded for balls placed into higher hoops, when alliances balance on mid-court “bridges” towards the end of the game, and when multiple alliances work together to balance on the white bridge located in the middle of the field.</p>

    <h2>Previous Years</h2>
    <p>In the 2011 FIRST Robotics Competition, MorTorq competed in “Logo Motion”. The objective of this game was to place inner tubes that were shaped like the triangle, circle, and square of the FIRST logo onto racks to win points, and, in the endgame, to deploy a smaller robot that climbed a pole.</p>
    <p>In 2010, MorTorq competed in the FRC game “Breakaway.” In this game, Robots drove over bumps in the field, navigated through tunnels, suspended themselves and other robots on towers, and directed soccer balls into goals.</p>
    <p>In 2009, MorTorq competed in the FRC game “Lunacy”. The objective of this game was to place as many game pieces as possible into the opposing side’s trailer in the allotted time.</p>
    <p>In 2008, “FIRST Overdrive” was the FRC game. In this game, teams attempted to do laps around a central barrier while trying to manipulate “trackballs” over and under overpasses for win additional points.</p>
    <p>The 2007 FRC game was “Rack 'n Roll.” In this game, alliances attempted to arrange inflatable game pieces shaped like toroidals on “The Rack”, a large device featuring three levels of hanging metal bars.</p>
    <p>In 2006, MorTorq competed in the FRC game “Aim High.” In “Aim High,” alliances scored points by shooting balls into goals and arranging their robots into certain positions on the playing field.</p>
    <p>In 2005, the FRC game was called “Triple Play.” The objective of this game was to place the game pieces, “Tetras,” in rows of three on large goals.</p>
  </div>
</div>