config/routes.rb
BHRobotics::Application.routes.draw do
  get "/welcome" => "welcome#index", :as => :welcome
  get "/webcast" => "welcome#webcast", :as => :webcast

  scope "/about" do
    get "mission" => "about#mission", :as => :mission

    get "members/sign-in" => "members#sign_in", :as => :sign_in
    post "members/sign-in" => "members#check_sign_in", :as => :check_sign_in
    get "members/sign-out" => "members#sign_out", :as => :sign_out
    get "members" => "members#index", :as => :members
    post "members" => "members#create"
    get "members/new" => "members#new", :as => :new_member
    get "members/:id" => "members#show", :as => :member
    put "members/:id" => "members#update"
    delete "members/:id" => "members#destroy"
    get "members/:id/edit" => "members#edit", :as => :edit_member

    scope "/robots" do
      get "rob-2" => "about#rob_2", :as => :rob_2
      get "strikert" => "about#strikert", :as => :strikert
      get "morbit" => "about#morbit", :as => :morbit
      get "orange-fever" => "about#orange_fever", :as => :orange_fever
      get "mad-max" => "about#mad_max", :as => :mad_max
      get "killer-katie" => "about#killer_katie", :as => :killer_katie
      get "norman-1" => "about#norman_1", :as => :norman_1
      get "mettabot" => "about#mettabot", :as => :mettabot
      root :to => "about#mettabot", :as => :robots
    end

    get "awards" => "about#awards", :as => :awards
    get "about-this-website" => "about#about_this_website", :as => :about_this_website
    root :to => "about#mission"
  end

  scope "/media" do
    get "documents" => "media#documents", :as => :documents
    get "calendar" => "media#calendar", :as => :calendar
    root :to => "media#documents"
    get "photos" => "media#photos", :as => :photos
  end

  scope "/partners" do
    get "wdi" => "partners#wdi", :as => :wdi
    get "larop" => "partners#larop", :as => :larop
    get "raytheon" => "partners#raytheon", :as => :raytheon
   # get "redman" => "partners#redman", :as => :redman
    get "asb" => "partners#asb", :as => :asb
    get "wire-edm" => "partners#wire_edm", :as => :wire_edm
    root :to => "partners#wdi"
  end

  scope "/community" do
    scope "/outreach" do
      get "car-show" => "community#car_show", :as => :car_show
      get "ttc" => "community#ttc", :as => :ttc
      get "rmd-charities" => "community#rmd_charities", :as => :rmd_charities
      get "engineering-day" => "community#engineering_day", :as => :engineering_day
      get "k8-contest" => "community#k8_contest", :as => :k8_contest
      get "mda" => "community#mda", :as => :mda
      get "cedars" => "community#cedars", :as => :cedars
      get "hm-breakfast" => "community#hm_breakfast", :as => :hm_breakfast
      get "other-outreach-events" => "community#other_outreach_events", :as => :other_outreach_events
      root :to => "community#outreach", :as => :outreach
    end

    root :to => "community#outreach"
  end

  scope "/first" do
    get "what-is-first" => "first#what_is_first", :as => :what_is_first
    get "rebound-rumble" => "first#rebound_rumble", :as => :rebound_rumble
    get "logomotion" => "first#logomotion", :as => :logomotion
    get "breakaway" => "first#breakaway", :as => :breakaway
    get "lunacy" => "first#lunacy", :as => :lunacy
    get "overdrive" => "first#overdrive", :as => :overdrive
    get "rack-n-roll" => "first#rack_n_roll", :as => :rack_n_roll
    get "aim-high" => "first#aim_high", :as => :aim_high
    get "triple-play" => "first#triple_play", :as => :triple_play
    get "game" => "first#game", :as => :game
    get "heroes-of-first" => "first#heroes_of_first", :as => :heroes_of_first
    get "creating-a-first-website" => "first#creating_a_first_website", :as => :creating_a_first_website
    root :to => "first#what_is_first"
  end

  scope "/welcome" do
    get "webcast" => "welcome#webcast", :as => :webcast
  end
  root :to => "welcome#index"
end

app/controllers/community_controller.rb
class CommunityController < ApplicationController
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/views/community/car_show.html.erb
<% title "Car Show" %>
<% page_class "outreach" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", outreach_path, :class => "back" %>
    <%= link_to "Forward", ttc_path, :class => "forward" %>
    <%= image_tag "outreach/car-show.jpeg", :alt => "Car Show" %>
  </section>

  <section class="information">
    <h1>Car Show</h1>
    <p>During past seasons, Team 1515 participated in the Classics for Charity Car Show, a charity function that raises money for a local education foundation. The team helped raise $50,000, attending corporate planning meetings, submitting ideas, and providing artwork and designs for promotional materials. The team also interacted with the community during the event. MorTorq team members worked in various booths and exhibited our robot to promote the team and FIRST. Children and adults visited us in droves, and even took turns driving one of our VEX Robots.</p>
  </section>
</section>

app/views/community/cedars.html.erb
<% title "Cedars Sinai Hospital & Mattel Children's Hospital" %>
<% page_class "outreach" %>

<div class="carousel">
  <section class="banner">
    <%= link_to "Back", k8_contest_path, :class => "back" %>
    <%= link_to "Forward", hm_breakfast_path, :class => "forward" %>
    <%= image_tag "outreach/cedars.jpeg", :alt => "Cedars Sinai Hospital & Mattel Children’s Hospital" %>
  </section>

  <section class="information">
    <h1>Cedars Sinai Hospital &amp; Mattel Children's Hospital</h1>
    <p>Reaching out to the younger community is an integral part of Team 1515's ideology. We spent the week before the holiday season making cards for the pediatric ward of Cedars Sinai. In past years, we have decorated the playrooms of the ward. We also went from room to room and visited all the children, giving each one their own handmade card. In addition, we had brought along a robot with the hopes of letting them see how fun robotics can be. Sadly, this year we were unable to go due to an outbreak of the flu and other diseases. Whether we can visit or not, every year MorTorq makes Christmas, Hannukah, and Valentine’s Day cards for the kids at Cedars-Sinai Hospital and Mattel’s Children’s Hospital, to lift their spirits and let them know that someone is on their side.</p>
  </section>
</div>

app/views/community/engineering_day.html.erb
<% title "Engineering Day" %>
<% page_class "outreach" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", rmd_charities_path, :class => "back" %>
    <%= link_to "Forward", mda_path, :class => "forward" %>
    <%= image_tag "outreach/engineering-day.jpeg", :alt => "Engineering Day" %>
  </section>

  <section class="information">
    <h1>Engineering Day</h1>
    <p>MorTorq's educational outreach is not limited to the Beverly Hills High School campus. In 2006, middle school students from all four Beverly Hills public schools competed against each other in a VEX competition designed by MorTorq members to excite them about the engineering process. In order to purchase parts, tools, and playing field material for the teams, MorTorq team members raised $4,000. A kickoff lunch was staged with 50 middle school students. At the kickoff, team leaders discussed the purpose of FIRST and rules to the VEX competition. The students had 10 weeks to build a working robot. MorTorq members came to their schools twice a week to help mentor and aid in the building process. On May 25, 2006 the VEX teams assembled in the high school gym to compete during MorTorq's first Engineering Day. Representatives from MorTorq corporate sponsors were on hand to teach the kids and their parents about engineering. The event was a huge success and resulted in a large influx of interest in the program by middle school students, their parents, and the community as a whole.</p>
  </section>
</section>

app/views/community/hm_breakfast.html.erb
<% title "Horace Mann Welcome Breakfast" %>
<% page_class "outreach" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", cedars_path, :class => "back" %>
    <%= link_to "Forward", other_outreach_events_path, :class => "forward" %>
    <%= image_tag "outreach/horace-mann.jpeg", :alt => "Horace Mann Welcome Breakfast" %>
  </section>

  <section class="information">
    <h1>Horace Mann Welcome Breakfast</h1>
    <p>On September 12, 2010, the Beverly Hills High School Robotics team attended the Horace Mann "Get to Know You" Breakfast. The breakfast featured many booths, including our own. The MorTorq booth advertised new robotics programs being offered at Horace Mann this year. Team 1515 displayed its VEX robot, a robot similar to the robots that will be created in the new programs. Kids and parents alike approached the MorTorq booth and asked questions about the two programs currently made available: Middle School Robotics Team, for 6th-8th graders, and Science Olympiad, for 4th -8th graders. The kids had a blast taking turns controlling the robot and talking with the high school team members about the program. Both programs are scheduled to last 3 months, with meetings around once a week. MorTorq's president, Alex Kern (12), spoke at the event, explaining to the attendees the importance of science and technology in schools and the goal of the programs. The programs seek to introduce elementary and middle school to the world of science and technology early on, and to hopefully motivate them to want to continue on with the program until they join the high school team at BHHS. The event was a huge success, with lots of students signing up for both programs. MorTorq looks forward to a great year, full of growth and success with the Middle School Robotics Team and the Science Olympiad!</p>
  </section>
</section>

app/views/community/k8_contest.html.erb
<% title "K-8 School Contest" %>
<% page_class "outreach" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", mda_path, :class => "back" %>
    <%= link_to "Forward", cedars_path, :class => "forward" %>
    <%= image_tag "outreach/k-8-contest.jpeg", :alt => "K-8 School Contest" %>
  </section>

  <section class="information">
    <h1>K-8 School Contest</h1>
    <p>A few years ago, MorTorq began The Design-A-Robot and Design-A-Rollercoaster contests, which were very successful. The top winners got to work alongside the team members from Team 1515. Due to the quality of all the entries, BHHS Robotics decided that all entries were winners and that every student that submitted an entry would be invited to a Future Engineer Day. It was great for the team to be able to share their interest and knowledge of FIRST and engineering with younger students and also to be looked up to as role models.</p>
  </section>
</section>

app/views/community/mda.html.erb
<% title "Muscular Dystrophy Association" %>
<% page_class "outreach" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", engineering_day_path, :class => "back" %>
    <%= link_to "Forward", k8_contest_path, :class => "forward" %>
    <%= image_tag "outreach/mda.jpeg", :alt => "Muscular Dystrophy Association" %>
  </section>

  <section class="information">
    <h1>Muscular Dystrophy Association</h1>
    <p>A cause very dear to the hearts of our team members is the fight against Muscular Dystrophy, which has afflicted the life of one of our alumni. Inspired to learn more and make a difference, our team has been fundraising and spreading the word about MDA for many years. In June 2007, we organized a Spare Change Drive to raise money for The Muscular Dystrophy Association (MDA). It was very successful and helped to raise over $1200 for the cause. In September 2007, our team was invited to participate in the Jerry Lewis Telethon for MDA, further aiding to fund necessary research. We were honored by the opportunity and were very pleased with the support we received in our fight to end MD. In 2008, Team 1515 and the BHHS Service learning class participated in the 20th annual "Shamrocks Against Dystrophy Drive,” raising about $600. This year, for the third year in a row, team members walked in the MDA Walk at CBS Studios.</p>
  </section>
</section>

app/views/community/other_outreach_events.html.erb
<% title "Outreach" %>
<% page_class "Other Outreach Events" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", hm_breakfast_path, :class => "back" %>
    <%= link_to "Forward", outreach_path, :class => "forward" %>
    <%= image_tag "outreach/other.jpg", :alt => "Other Outreach Events" %>
  </section>

  <section class="information">
    <h1>Other Outreach Events</h1>

    <h2>Albion Street</h2>
    <p>This year, several MorTorq team members collaborated with the Beverly Hills High School Service Learning class to hand out Christmas presents to children at Albion Street Elementary School following a school-wide toy drive.</p>

    <h2>Sock Drive</h2>
    <p>From December 5, 2012 to December 16, Robotics members engineered and managed a district-wide sock drive incorporating the high school and district middle schools. Members traveled to each middle school, solicited new sock donations, posted and passed out flyers, and delivered the sock donations to the Salvation Army in Los Angeles.</p>

    <h2>AIDS Project Los Angeles</h2>
    <p>This year, for the third year in a row, MorTorq volunteered with the Aids Project Los Angeles at the LA AIDS Walk. Team members served in all sorts of capacities, from registering walkers to cheering on participants and writing receipts to support the search for a cure.</p>

    <h2>Darfur Dream Team</h2>
    <p>For our third year this year, MorTorq is proud to be a sister school to the Obama School in Sudan, Chad, through the Darfur Dream Team Foundation. The Darfur Dream Team Foundation supplies textbooks and other important supplies to schools for refugees from Darfur living in camps in Chad. MorTorq is proud to represent FIRST to these refugees abroad, and this year held a schoolwide fundraiser to benefit the Foundation.</p>

    <h2>Hygiene Drive</h2>
    <p>To start the New Year clean, MorTorq held a January Hygiene drive to benefit West Los Angeles PATH (People Assisting The Homeless). MorTorq placed collection boxes in each of the high school’s counseling offices and the main office, posted flyers around the school, and gave presentations to classes to solicit donations. MorTorq delivered hundreds of hygiene items to a very happy PATH staff!</p>

    <h2>Restaurant Fundraisers</h2>
    <p>To cover competition costs, the team holds fundraisers at both CPK and Sharkey’s, where members of the team and community dine, have fun, and contribute at the same time.</p>

    <h2>BH Proclamation</h2>
    <p>Whereas, for three years the Beverly Hills High School Robotics Team has participated in numerous science and technology competitions and events, winning many awards and accolades; and</p>
    <p>Whereas, members of the Beverly Hills High School Robotics Team are involved in many science and technology projects and learn skills in web design, animation, computer programming, engineering, television production and writing: and</p>
    <p>Whereas, the Beverly Hills High School Robotics Team has raised money for worthy causes and taught in workshops, inspiring young people to excel in math, engineering, science and technology.</p>
    <p>Now, Therefore, I Stephen P. Webb, Mayor of the City of Beverly Hills, do hereby congratulate the Beverly Hills High School Robotics Team on its many awards and accomplishments, and further reconize the team's important role in encouraging excellence in science and technology,</p>
    <p>Stephen P. Webb, Mayor</p>
  </section>
</section>

app/views/community/outreach.html.erb
<% title "Outreach" %>
<% page_class "outreach" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", other_outreach_events_path, :class => "back" %>
    <%= link_to "Forward", car_show_path, :class => "forward" %>
    <%= image_tag "outreach/outreach.jpg", :alt => "Outreach" %>
  </section>

  <section class="information">
    <h1>Outreach</h1>
    <p>For the past nine years, Team 1515 has participated in several community outreach events. Spanning from volunteering at car shows to playing with patients at Cedar Sinai, Mortorq has consistently demonstrated a thirst for community involvement. Our enthusiastic team members have always found a spot in their heart for giving back to the community that gave them so much, and our outreach efforts seem to double each year. Organizations that MorTorq has collaborated with include the Car Show, Techno-tainment Camp, the Ronald McDonald House Charity, the Muscular Dystrophy Association, Aids Project Los Angeles, Cedars Sinai Hospital, Albion Street Schools, PATH Homeless Shelter, the Salvation Army, the Darfur Dream Team, and many more.</p>
  </section>
</section>

app/views/community/rmd_charities.html.erb
<% title "Ronald McDonald House Charities" %>
<% page_class "outreach" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", ttc_path, :class => "back" %>
    <%= link_to "Forward", engineering_day_path, :class => "forward" %>
    <%= image_tag "outreach/ronald-mcdonald.jpeg", :alt => "Ronald McDonald House Charities" %>
  </section>

  <section class="information">
    <h1>Ronald McDonald House Charities</h1>
    <p>MorTorq has been collaborating with the Ronald McDonald House for over six years now. The team has collected several thousand recyclables over the span of several robotics seasons, and each year we use the money we raise from recycling the cans to purchase food to prepare several meals at the Ronald McDonald House Charities. Everyone on Team 1515 enjoys seeing the faces of the kids when we show up with a small VEX robot for them to play with, color pictures of robots, and talk about science with the kids.</p>
  </section>
</section>

app/views/community/ttc.html.erb
<% title "TechnoTainment Camp" %>
<% page_class "outreach" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", car_show_path, :class => "back" %>
    <%= link_to "Forward", rmd_charities_path, :class => "forward" %>
    <%= image_tag "outreach/ttc.jpeg", :alt => "TechnoTainment Camp" %>
  </section>

  <section class="information">
    <h1>TechnoTainment Camp</h1>
    <p>MorTorq believes in reaching out to kids to inspire them with science and engineering. One way we do this is through presentations and assistance at PlanetBravo's Techno-tainment camp. We displayed our award-winning robot to the campers during multiple sessions of the camp and assisted with the robotics courses concentrating on the Vex platform. MorTorq has developed a strong relationship with the camp over the years and we look forward to continuing our involvement with its campers and staff.</p>
  </section>
</section>