config/routes.rb
BHRobotics::Application.routes.draw do
  get "/welcome" => "welcome#index", :as => :welcome
  get "/webcast" => "welcome#webcast", :as => :webcast

  scope "/about" do
    get "mission" => "about#mission", :as => :mission

    get "members/sign-in" => "members#sign_in", :as => :sign_in
    post "members/sign-in" => "members#check_sign_in", :as => :check_sign_in
    get "members/sign-out" => "members#sign_out", :as => :sign_out
    get "members" => "members#index", :as => :members
    post "members" => "members#create"
    get "members/new" => "members#new", :as => :new_member
    get "members/:id" => "members#show", :as => :member
    put "members/:id" => "members#update"
    delete "members/:id" => "members#destroy"
    get "members/:id/edit" => "members#edit", :as => :edit_member

    scope "/robots" do
      get "rob-2" => "about#rob_2", :as => :rob_2
      get "strikert" => "about#strikert", :as => :strikert
      get "morbit" => "about#morbit", :as => :morbit
      get "orange-fever" => "about#orange_fever", :as => :orange_fever
      get "mad-max" => "about#mad_max", :as => :mad_max
      get "killer-katie" => "about#killer_katie", :as => :killer_katie
      get "norman-1" => "about#norman_1", :as => :norman_1
      get "mettabot" => "about#mettabot", :as => :mettabot
      root :to => "about#mettabot", :as => :robots
    end

    get "awards" => "about#awards", :as => :awards
    get "about-this-website" => "about#about_this_website", :as => :about_this_website
    root :to => "about#mission"
  end

  scope "/media" do
    get "documents" => "media#documents", :as => :documents
    get "calendar" => "media#calendar", :as => :calendar
    root :to => "media#documents"
    get "photos" => "media#photos", :as => :photos
  end

  scope "/partners" do
    get "wdi" => "partners#wdi", :as => :wdi
    get "larop" => "partners#larop", :as => :larop
    get "raytheon" => "partners#raytheon", :as => :raytheon
   # get "redman" => "partners#redman", :as => :redman
    get "asb" => "partners#asb", :as => :asb
    get "wire-edm" => "partners#wire_edm", :as => :wire_edm
    root :to => "partners#wdi"
  end

  scope "/community" do
    scope "/outreach" do
      get "car-show" => "community#car_show", :as => :car_show
      get "ttc" => "community#ttc", :as => :ttc
      get "rmd-charities" => "community#rmd_charities", :as => :rmd_charities
      get "engineering-day" => "community#engineering_day", :as => :engineering_day
      get "k8-contest" => "community#k8_contest", :as => :k8_contest
      get "mda" => "community#mda", :as => :mda
      get "cedars" => "community#cedars", :as => :cedars
      get "hm-breakfast" => "community#hm_breakfast", :as => :hm_breakfast
      get "other-outreach-events" => "community#other_outreach_events", :as => :other_outreach_events
      root :to => "community#outreach", :as => :outreach
    end

    root :to => "community#outreach"
  end

  scope "/first" do
    get "what-is-first" => "first#what_is_first", :as => :what_is_first
    get "rebound-rumble" => "first#rebound_rumble", :as => :rebound_rumble
    get "logomotion" => "first#logomotion", :as => :logomotion
    get "breakaway" => "first#breakaway", :as => :breakaway
    get "lunacy" => "first#lunacy", :as => :lunacy
    get "overdrive" => "first#overdrive", :as => :overdrive
    get "rack-n-roll" => "first#rack_n_roll", :as => :rack_n_roll
    get "aim-high" => "first#aim_high", :as => :aim_high
    get "triple-play" => "first#triple_play", :as => :triple_play
    get "game" => "first#game", :as => :game
    get "heroes-of-first" => "first#heroes_of_first", :as => :heroes_of_first
    get "creating-a-first-website" => "first#creating_a_first_website", :as => :creating_a_first_website
    root :to => "first#what_is_first"
  end

  scope "/welcome" do
    get "webcast" => "welcome#webcast", :as => :webcast
  end
  root :to => "welcome#index"
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/about_this_website.html.erb
<% title "About this Website" %>
<% page_class "about-this-website" %>

<header>
  <%= image_tag "headers/about-this-website.jpg", :alt => "About this Website" %>
</header>

<section class="intro">
  <h1>About this Website</h1>
  <p>Hello there! Thanks for visiting our site. We, the website team, spent a lot of time creating it. Every year, our mission is to make the site an informative portal about our team and the FIRST Robotics program in general. Want to learn how it was built? Well, you've found the right place!</p>
</section>

<section class="website-information">
  <div class="column-1">
    <h2>Student Designed, Student Built</h2>
    <p>Students of the website team have built the entire site that you're currently viewing. This year, we decided to redesign the entire site, adding tons of new sections and updating the minimalist design with something more exciting. At the beginning of season, we did content planning for each page and developed over 20 user scenarios that we had to target. Afterward, we split into two groups. One group handled content development and collected the all of the information for each page. The other group handled the visuals of each page, creating assets that are used throughout the site. The groups collaborated and the website slowly came together.</p>
    <p>Along the way, senior team members taught the newer members how to program with the web standards HTML and CSS. This high degree of student particpation helped the website team become extremely proficient with modern web technologies, and allowed each team member to contribute to the site without needing outside help. Rather than using existing content management systems (CMSes), such as Wordpress, early on we opted for a far more flexible approach: building our own content management system in Ruby on Rails, an extremely popular website framework. This has enabled the team to rapidly iterate over our new content layouts while retaining the ease of use one finds in a CMS.</p>

    <h2>Helping Others</h2>
    <p>Open sourcing our website has been the best decision our website team has ever made. We wanted to give back even more to the FIRST community, though, so we wrote a <%= link_to "&lsquo;getting started&rsquo; guide for other FIRST teams that want to build their own websites", creating_a_first_website_path %>. Our team also decided to give away our marketing materials and Build manuals for free so that other teams may use them as inspiration. You can find these in the <%= link_to "documents section", documents_path %>.</p>
  </div>

  <div class="column-2">
    <h2>Supporting Emerging Web Standards</h2>
    <p>Before we wrote a single line of code for the website, we had to decide on which new browser technologies we were going to use. Members of our team are huge proponents of the fast-moving HTML5 standard (we &hearts; you, Ian Hickinson!) and its accompanying CSS3 standard. As such, we decided to have our site progressively enhanced, pushing as many of the visual frills in CSS as we could. If you're looking at this website through a modern web browser, good on you! You're experiencing this site&#8212;and the web&#8212;as it was intended to be viewed!</p>
    <p>While we understand that using newer standards such as HTML5 and CSS3 involves removing support for older browsers such as Internet Explorer 6 and 7, we accept that tradeoff in light of how much development time we have saved as a result. We officially support the two latest major versions of Google Chrome, Apple Safari, Mozilla Firefox, and Microsoft Internet Explorer. This gives over 98% of our viewers a pixel-perfect experience.</p>

    <h2>Entirely Open Source</h2>
    <p>FIRST is all about Gracious Professionalism. This philosophy aligns perfectly with the spirit of free and open source software. Rather than closing off our website's source from the world, our team decided to release it for free so that other teams may read, modify, and use the code for their own websites. The openness of our website ensures that every team member has the ability to improve upon the site. In fact, if you'd like to read it or submit a modification to the site, you can do so right now in our <%= link_to "GitHub repository", "https://github.com/CapnKernul/bhrobotics.com" %>. If you're part of a FIRST team, feel free to use any of our website's code or assets to build your own team's site. Need help getting started? <%= link_to "We can help", creating_a_first_website_path %>. </p>
  </div>
</section>

<hr />

<section class="acknowledgements">
  <h2>Acknowledgements</h2>
  <p>We'd like to thank Zach Kahn, <%= link_to "Alex Fischoff", "http://www.afischoff.com/" %>, <%= link_to "Alex Kern", "http://kernul.com" %>, <%= link_to "Raj Vir", "http://rjvir.com" %>, <%= link_to "Joseph Martin", "http://www.atumcreative.com/" %>, <%= link_to "Mehrzad Farnoosh", "http://vorpd.com" %>, and all other website members for making this website possible. You rock. &hearts;
</section>

app/views/about/awards.html.erb
<% title "Awards" %>
<% page_class "awards" %>

<header>
  <%= image_tag "headers/awards.jpg", :alt => "Awards" %>
</header>

<section class="information">
  <h1>Awards</h1>
  <h2>2011-2012:</h2>
  <ul>
    <li>2012 Excellence in Design Award Sponsored by Autodesk - 3D Design Category Finalist</li>  
    <li>Gracious Professionalism (Los Angeles, CA)</li>
    <li> Safety Star of the Day - Adar Thau (Los Angeles, CA)</li>
  </ul>  
  
  <h2>2010-2011: FIRST in M.O.T.I.O.N.</h2>
  <ul>
    <li>Regional Innovation in Control Award (Los Angeles, CA)</li>
    <li>Regional Industrial Safety Award (Los Angeles, CA)</li>
    <li>Regional Finalist Award (Los Angeles, CA)</li>
    <li>Regional Innovation in Control Award (Denver, CO)</li>
    <li>Safety Recognition (Denver, CO)</li>
  </ul>

  <h2>2009-2010: Go for the G.O.A.L.</h2>
  <ul>
    <li>Chairman's Award (Los Angeles, CA)</li>
    <li>Regional Championship (Portland, OR)</li>
    <li>Motorola Quality Award (Portland, OR)</li>
    <li>Autodesk Excellence in Script/Sound</li>
  </ul>

  <h2>2008-2009: Shoot for the Moon</h2>
  <ul>
    <li>Safety Award (Denver, CO)</li>
    <li>Team Spirit Award (Denver, CO)</li>
    <li>Judges Award (Los Angeles, CA)</li>
  </ul>

  <h2>2007-2008: Overdrive into Action</h2>
  <ul>
    <li>FIRST Tech Challenge Connect Award (Los Angeles, CA)</li>
    <li>FIRST Tech Challenge Winning Alliance Award (Los Angeles, CA)</li>
  </ul>

  <h2>2006-2007: Spreading the Word</h2>
  <ul>
    <li>Regional Finalist (Denver, CO)</li>
    <li>DaimlerChrysler Team Spirit Award (Denver, CO)</li>
    <li>Imagery Award (Los Angeles, CA)</li>
    <li>Autodesk Visualization Award (Los Angeles, CA)</li>
    <li>Website Award (Los Angeles, CA)</li>
  </ul>

  <h2>2005-2006: Setting up Shop</h2>
  <ul>
    <li>2006 SCRRF Pre-Ship Scrimmage Champions</li>
    <li>7th Place (Las Vegas, NV)</li>
    <li>Autodesk Visualization Award (Los Angeles, CA)</li>
    <li>Kleiner Perkins Caufield &amp; Byers Entrepreneurship Award (Los Angeles, CA)</li>
    <li>Kleiner Perkins Caufield &amp; Byers Entrepreneurship Award (Las Vegas, NV)</li>
    <li>Engineering Inspiration Award presented by Team 4</li>
  </ul>

  <h2>2004-2005: Building a Foundation</h2>
  <ul>
    <li>Rookie Inspiration Award (Denver, CO)</li>
    <li>Rookie All-Star Award (Los Angeles, CA)</li>
    <li>3rd Place (Denver, CO)</li>
    <li>3rd Place (Los Angeles, CA)</li>
    <li>2nd Highest Rookie Team (Los Angeles, CA)</li>
    <li>2005 Fall Classic Drag Race S.C.R.R.F Award at Chatsworth High School</li>
    <li>64th place in the world (Atlanta, GA)</li>
    <li>Rookie Excellence Award from Team 254</li>
    <li>Aesthetics Award from Team 22</li>
  </ul>
</section>

app/views/about/business.html.erb
<% title "Business" %>

<header>
  <p>The Business Team</p>
</header>

<section class="intro">
  <h1>About the Business Team</h1>
  <p>Hello there! Welcome to the business page</p>
  <!-- add more info later -->
</section> 

app/views/about/index.html.erb
<h1>Vorpd</h1>

app/views/about/killer_katie.html.erb
<% title "Killer Katie" %>
<% page_class "robots" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", mad_max_path, :class => "back" %>
    <%= link_to "Forward", norman_1_path, :class => "forward" %>
    <%= image_tag "robots/2006.jpg", :alt => "Outreach" %>
  </section>

  <section class="information">
    <h1>2006: Killer Katie</h1>
    <ul>
      <li>Nicknames: Water Bottle</li>
      <li>Weight: 119 lbs.</li>
      <li>Height: 59 in.</li>
      <li>Width: 27.5 in.</li>
      <li>Length: 37 in.</li>
      <li>Drive Train: 4-wheel tank drive</li>
      <li>FIRST Game: Aim High</li>
      <li>Explanation: Killer Katie shot balls, picked up from the ground via a conveyor belt, into holes of varying placements on the wall.</li>
    </ul>
  </section>
</section>

app/views/about/mad_max.html.erb
<% title "Mad Max" %>
<% page_class "robots" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", orange_fever_path, :class => "back" %>
    <%= link_to "Forward", killer_katie_path, :class => "forward" %>
    <%= image_tag "robots/2007.jpg", :alt => "Outreach" %>
  </section>

  <section class="information">
    <h1>2007: Mad Max</h1>
    <ul>
      <li>Nicknames: Black Hawk, The MON</li>
      <li>Weight: 113 lbs.</li>
      <li>Height: 48 in.</li>
      <li>Width: 27.5 in.</li>
      <li>Length: 37 in.</li>
      <li>Drive Train: 6-wheel tank drive</li>
      <li>FIRST Game: Rack 'n Roll</li>
      <li>Explanation: Mad Max used a nine-foot arm to pick up pegs and place them on circular peg structures, playing in a game of tic-tac-toe while creating tic-tac-toe formations.</li>
    </ul>
  </section>
</section>

app/views/about/mettabot.html.erb
<% title "MettaBot World Peace" %>
<% page_class "robots" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", norman_1_path, :class => "back" %>
    <%= link_to "Forward", rob_2_path, :class => "forward" %>
    <%= image_tag "robots/2012.JPG", :alt => "Bot" %>
  </section>

  <section class="information">
    <h1>2012: MettaBot World Peace</h1>
    <ul>
      <li>Nicknames: Chainbreaker, Chain Reaction, FIRST</li>
      <li>Weight: 120 lbs.</li>
      <li>Height: 58 in.</li>
      <li>Width: 26 in.</li>
      <li>Length: 30 in.</li>
      <li>Drive Train: 6 Wheel Drive dropped center</li>
      <li>FIRST Game: Rebound Rumble</li>
      <li>Explanation: With close to an 18 fps traveling speed, the robot utilizes a dual stage conveyor system which allows for exactly 3 balls in each stage. The turreted dual-FP shooter shoots the ball approximately 25'. 100% of the processing is done offboard, so the robot only follows directions given to it, not having any itself.</li>
    </ul>
  </section>
</section>

app/views/about/morbit.html.erb
<% title "MorBit" %>
<% page_class "robots" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", strikert_path, :class => "back" %>
    <%= link_to "Forward", orange_fever_path, :class => "forward" %>
    <%= image_tag "robots/2009.jpg", :alt => "Outreach" %>
  </section>

  <section class="information">
    <h1>2009: MorBit</h1>
    <ul>
      <li>Nicknames: The Turret</li>
      <li>Weight: 120 lbs.</li>
      <li>Height: 60 in.</li>
      <li>Width: 32 in.</li>
      <li>Length: 37 in.</li>
      <li>Drive Train: 4-wheel tank drive</li>
      <li>FIRST Game: Lunacy</li>
      <li>Explanation: Lunacy's field was designed from a material giving the robots reduced traction, simulating low gravity on the surface of the moon. MorBit spun and threw balls, or "moon rocks," into carts behind each opposing robot to score points.</li>
    </ul>
  </section>
</section>

app/views/about/norman_1.html.erb
<% title "Norman I" %>
<% page_class "robots" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", killer_katie_path, :class => "back" %>
    <%= link_to "Forward", mettabot_path, :class => "forward" %>
    <%= image_tag "robots/2005.jpg", :alt => "Outreach" %>
  </section>

  <section class="information">
    <h1>2005: Norman I</h1>
    <ul>
      <li>Nicknames: Ziptie</li>
      <li>Weight: 106 lbs.</li>
      <li>Height: 59 in.</li>
      <li>Width: 27.5 in.</li>
      <li>Length: 37 in.</li>
      <li>Drive Train: 4-wheel tank drive</li>
      <li>FIRST Game: Triple Play</li>
      <li>Explanation: Norman I used a hook on the end of its arm to pick up and stack tetrahedral PVC pyramids as high as possible.</ul>
  </section>
</section>

app/views/about/orange_fever.html.erb
<% title "Orange Fever" %>
<% page_class "robots" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", morbit_path, :class => "back" %>
    <%= link_to "Forward", mad_max_path, :class => "forward" %>
    <%= image_tag "robots/2008.jpg", :alt => "Outreach" %>
  </section>

  <section class="information">
    <h1>2008: Orange Fever</h1>
    <ul>
      <li>Nicknames: ChoBot, The Black Hole</li>
      <li>Weight: 120 lbs.</li>
      <li>Height: 59 in.</li>
      <li>Width: 27 in.</li>
      <li>Length: 37 in.</li>
      <li>Drive Train: 6-wheel tank drive</li>
      <li>FIRST Game: FIRST Overdrive</li>
      <li>Explanation: The robot was designed to go around a track similar to a NASCAR racecar track while picking up and throwing a 40 in diameter yoga ball over a 6 foot tall overpass.</li>
    </ul>
  </section>
</section>

app/views/about/rob_2.html.erb
<% title "ROB 2.0" %>
<% page_class "robots" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", mettabot_path, :class => "back" %>
    <%= link_to "Forward", strikert_path, :class => "forward" %>
    <%= image_tag "robots/2011.jpg", :alt => "Outreach" %>
  </section>

  <section class="information">
    <h1>2011: ROB 2.0</h1>
    <ul>
      <li>Nicknames: BOTH HANDS</li>
      <li>Weight: 120 lbs.</li>
      <li>Height: 28 in.</li>
      <li>Width: 28 in.</li>
      <li>Length: 38 in.</li>
      <li>Drive Train: 4-wheel mecanum drive</li>
      <li>FIRST Game: Logomotion</li>
      <li>Explanation: ROB 2.0 had an elevator-pulley system and used an arm with a claw at the end to pick up tubes to place exactly on target pegs.</li>
    </ul>
  </section>
</section>

app/views/about/strikert.html.erb
<% title "StrikerT" %>
<% page_class "robots" %>

<section class="carousel">
  <section class="banner">
    <%= link_to "Back", rob_2_path, :class => "back" %>
    <%= link_to "Forward", morbit_path, :class => "forward" %>
    <%= image_tag "robots/2010.jpg", :alt => "Outreach" %>
  </section>

  <section class="information">
    <h1>2010: StrikerT</h1>
    <ul>
      <li>Nicknames: MechBot</li>
      <li>Weight: 120 lbs.</li>
      <li>Height: 30 in.</li>
      <li>Width: 28 in.</li>
      <li>Length: 38 in.</li>
      <li>Drive Train: 4-wheel mecanum drive</li>
      <li>FIRST Game: Breakaway</li>
      <li>Explanation: Breakaway was very similar to soccer: robots on the field would kick balls into each of its goals. StrikerT was a defensive robot. Its drive train was extremely strong so that it could easily stop other robots from scoring.</li>
    </ul>
  </section>
</section>

app/views/about/website.html.erb
<title>Website</title>