config/routes.rb
BHRobotics::Application.routes.draw do
  get "/welcome" => "welcome#index", :as => :welcome
  get "/webcast" => "welcome#webcast", :as => :webcast

  scope "/about" do
    get "mission" => "about#mission", :as => :mission

    get "members/sign-in" => "members#sign_in", :as => :sign_in
    post "members/sign-in" => "members#check_sign_in", :as => :check_sign_in
    get "members/sign-out" => "members#sign_out", :as => :sign_out
    get "members" => "members#index", :as => :members
    post "members" => "members#create"
    get "members/new" => "members#new", :as => :new_member
    get "members/:id" => "members#show", :as => :member
    put "members/:id" => "members#update"
    delete "members/:id" => "members#destroy"
    get "members/:id/edit" => "members#edit", :as => :edit_member

    scope "/robots" do
      get "rob-2" => "about#rob_2", :as => :rob_2
      get "strikert" => "about#strikert", :as => :strikert
      get "morbit" => "about#morbit", :as => :morbit
      get "orange-fever" => "about#orange_fever", :as => :orange_fever
      get "mad-max" => "about#mad_max", :as => :mad_max
      get "killer-katie" => "about#killer_katie", :as => :killer_katie
      get "norman-1" => "about#norman_1", :as => :norman_1
      get "mettabot" => "about#mettabot", :as => :mettabot
      root :to => "about#mettabot", :as => :robots
    end

    get "awards" => "about#awards", :as => :awards
    get "about-this-website" => "about#about_this_website", :as => :about_this_website
    root :to => "about#mission"
  end

  scope "/media" do
    get "documents" => "media#documents", :as => :documents
    get "calendar" => "media#calendar", :as => :calendar
    root :to => "media#documents"
    get "photos" => "media#photos", :as => :photos
  end

  scope "/partners" do
    get "wdi" => "partners#wdi", :as => :wdi
    get "larop" => "partners#larop", :as => :larop
    get "raytheon" => "partners#raytheon", :as => :raytheon
   # get "redman" => "partners#redman", :as => :redman
    get "asb" => "partners#asb", :as => :asb
    get "wire-edm" => "partners#wire_edm", :as => :wire_edm
    root :to => "partners#wdi"
  end

  scope "/community" do
    scope "/outreach" do
      get "car-show" => "community#car_show", :as => :car_show
      get "ttc" => "community#ttc", :as => :ttc
      get "rmd-charities" => "community#rmd_charities", :as => :rmd_charities
      get "engineering-day" => "community#engineering_day", :as => :engineering_day
      get "k8-contest" => "community#k8_contest", :as => :k8_contest
      get "mda" => "community#mda", :as => :mda
      get "cedars" => "community#cedars", :as => :cedars
      get "hm-breakfast" => "community#hm_breakfast", :as => :hm_breakfast
      get "other-outreach-events" => "community#other_outreach_events", :as => :other_outreach_events
      root :to => "community#outreach", :as => :outreach
    end

    root :to => "community#outreach"
  end

  scope "/first" do
    get "what-is-first" => "first#what_is_first", :as => :what_is_first
    get "rebound-rumble" => "first#rebound_rumble", :as => :rebound_rumble
    get "logomotion" => "first#logomotion", :as => :logomotion
    get "breakaway" => "first#breakaway", :as => :breakaway
    get "lunacy" => "first#lunacy", :as => :lunacy
    get "overdrive" => "first#overdrive", :as => :overdrive
    get "rack-n-roll" => "first#rack_n_roll", :as => :rack_n_roll
    get "aim-high" => "first#aim_high", :as => :aim_high
    get "triple-play" => "first#triple_play", :as => :triple_play
    get "game" => "first#game", :as => :game
    get "heroes-of-first" => "first#heroes_of_first", :as => :heroes_of_first
    get "creating-a-first-website" => "first#creating_a_first_website", :as => :creating_a_first_website
    root :to => "first#what_is_first"
  end

  scope "/welcome" do
    get "webcast" => "welcome#webcast", :as => :webcast
  end
  root :to => "welcome#index"
end

app/views/layouts/_google_analytics.html.erb
<script>
  var _gaq=[["_setAccount","UA-21365987-1"],["_trackPageview"]];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
  s.parentNode.insertBefore(g,s)}(document,"script"));
</script>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <%= csrf_meta_tags %>

    <title><%= render_title %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <div id="top-background"></div>
    <div id="loader">Loading...</div>
        <header id="header">
      <%= link_to "Home", welcome_path, :id => "logo" %>
      <div id="social-media-links">
        <% link_to "Facebook", "http://www.facebook.com/pages/BHHS-Robotics/170502726325973", :class => "facebook" %>
        &middot;
        <% link_to "Twitter", "http://twitter.com/bhrobotics1515", :class => "twitter" %>
        &middot;
        <%= link_to "Blog", "http://bhrobotics.tumblr.com" %>
        &middot;
        <%= link_to "Subscribe", "http://visitor.r20.constantcontact.com/d.jsp?llr=nmavm8bab&p=oi&m=1101504610701" %>
        &middot;
        <%= link_to "Contact", "mailto:contact@bhrobotics.com" %>
		&middot;
		<%= link_to "Cal", "media/calendar" %>
      </div>
      <div id="first-link">
        <a href="http://www.usfirst.org">&raquo; Go to <img src="/assets/first-logo-header.png" alt="FIRST logo" /> <em>FIRST</em></a>
      </div>
      <nav id="nav">
        <ol>
          <li class="section">
            <%= link_to "About", mission_path %>
            <ol class="subsections">
              <li><%= link_to "Mission", mission_path %></li>
              <li><% link_to "Members", members_path %></li>
              <li><%= link_to "Robots", robots_path %></li>
              <li><%= link_to "Awards", awards_path %></li>
              <li><%= link_to "About this Website", about_this_website_path %></li>
            </ol>
          </li>
          <li class="section">
            <%= link_to "Media", documents_path %>
            <ol class="subsections">
              <li><%= link_to "Documents", documents_path %></li>
              <li><%= link_to "Photos", "https://picasaweb.google.com/113247014624505710959" %></li>
              <li><%= link_to "Videos", "http://vimeo.com/mortorq/videos" %></li>
                            
<li><%= link_to "Calendar", calendar_path %></li>
			  <li><%= link_to "Editor's Choice Photos", photos_path %></li>
            </ol>
          </li>
          <li class="section">
            <%= link_to "Partners", wdi_path %>
            <ol class="subsections">
              <li><%= link_to "Walt Disney Imagineering", wdi_path %></li>
              <li><%= link_to "Raytheon", raytheon_path %></li>
              <li><%= link_to "LA County ROP", larop_path %></li>
              <li><%= link_to "Wire Tech EDM", wire_edm_path %></li>
              <li><%= link_to "ASB", asb_path %></li>
            </ol>
          </li>
          <li class="section">
            <%= link_to "Community", outreach_path %>
            <ol class="subsections">
              <li><%= link_to "Outreach", outreach_path %></li>
              <li><%= link_to "Blog", "http://bhrobotics.tumblr.com" %></li>
              <li><%= link_to "Facebook", "http://www.facebook.com/pages/BHHS-Robotics/170502726325973" %></li>
              <li><%= link_to "Twitter", "http://twitter.com/bhrobotics1515" %></li>
            </ol>
          </li>
          <li class="section">
            <%= link_to "<em>FIRST</em>".html_safe, what_is_first_path %>
            <ol class="subsections">
              <li><%= link_to "What is FIRST?", what_is_first_path %></li>
              <li><%= link_to "Ultimate Ascent", game_path %></li>
              <li><%= link_to "Previous Years", logomotion_path %></li>
              <li><%= link_to "Heroes of FIRST", heroes_of_first_path %></li>
              <li><%= link_to "Creating a FIRST Website", creating_a_first_website_path %></li>
            </ol>
          </li>
        </ol>
      </nav>
    </header>

    <div id="main" role="main">
      <div class="<%= render_page_class %>">
        <%= yield %>
      </div>
    </div>

    <footer id="footer">
      <div id="awards">
        <img src="/assets/website-awards/2005-excellence.gif" alt="2005 Web Site Excellence Award" />
        <img src="/assets/website-awards/2007-excellence.gif" alt="2007 Web Site Excellence Award" />
        <img src="/assets/website-awards/2007-los-angeles.gif" alt="2007 Best Web Site - Los Angeles Regional" />
        <img src="/assets/website-awards/2008-excellence.gif" alt="2008 Web Site Excellence Award" />
        <img src="/assets/website-awards/2008-arizona.gif" alt="2008 Best Web Site - Arizona Regional" />
        <img src="/assets/website-awards/2008-los-angeles.gif" alt="2008 Best Web Site - Los Angeles Regional" />
        <img src="/assets/website-awards/2009-excellence.jpg" alt="2009 Web Site Excellence Award" />
      </div>
      <p id="copyright">&copy; Copyright 2005-<%= Time.now.year %> BHRobotics. All rights reserved.</p>
      <p class="misc"><a href="http://validator.w3.org/check?uri=http%3A%2F%2Fbhrobotics.com%2F">&#10003; Valid HTML5</a> &middot; <a href="http://www.CynthiaSays.com/org/cynthiatested.htm">Cynthia Tested!</a> &middot; <a href="https://github.com/CapnKernul/bhrobotics.com">Entirely open source</a> &middot; <%= link_to "Made with &hearts;".html_safe, about_this_website_path %> &middot; <a href="http://www.usfirst.org"><img src="/assets/first-logo-footer.png" alt="FIRST logo" /></a></p>

    </footer>

    <%= render :partial => "layouts/google_analytics" %>
  </body>
</html>

app/views/layouts/pjax.html.erb
<div class="<%= render_page_class %>">
  <%= yield %>
</div>